Adding number support to slugs
ComfortablyCoding/strapi-plugin-slugify pull request #54
Opened 2022-04-13 23:41 UTC by kibblerz

Adding support for numbers in the slug. It's a simple change, but quite useful to be able to use numbers in the slug fields.

2022-04-14 04:11 UTC, ComfortablyCoding commented
Can you explain further what this should be accomplishing? Using a number field as a reference is already supported.

2022-04-14 13:12 UTC, kibblerz commented
It does not, the slug ends up empty, or the reference field is skipped if skipUndefinedReferences is enabled. Numbers do not have a length property, so it is seen as undefined.

2022-04-21 06:02 UTC, ComfortablyCoding commented
Alright, makes sense. Thanks for catching and reporting it. Will review it over the weekend.

2022-04-25 01:18 UTC, ComfortablyCoding requested changes

2022-04-25 01:18 UTC, ComfortablyCoding commented on server/services/slug-service.js
> +			.filter((r) => (typeof data[r] !== 'undefined' && data[r].length) || (typeof data[r] === 'number'))
```suggestion
			.filter((r) => (typeof data[r] !== 'undefined' && (data[r].length || typeof data[r] === 'number'))
```

2022-04-25 01:22 UTC, ComfortablyCoding commented
@kibblerz ,

Please resolve the suggested change and remove the changes to lines 36 & 38. Once completed I will merge.

2022-10-24 05:34 UTC, ComfortablyCoding commented
Closing as this will be fixed by #78

2022-10-24 05:34 UTC, closed without merging